<%--
  Created by IntelliJ IDEA.
  User: Gongle
  Date: 13-7-24
  Time: 下午4:53
  To change this template use File | Settings | File Templates.
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<html>
<head>
    <title>web fonts</title>
    <link href="${ctx}/static/assets/css/icons/splashy.css" type="text/css/" rel="stylesheet"/>
    <link href="${ctx}/static/assets/css/icons/icsw2_16.css" type="text/css/" rel="stylesheet"/>
</head>
<body>

<div class="w-box">
<div class="w-box-header">
    <h4>Icon Sweet 2</h4>
</div>
<div class="w-box-content cnt_a">
<div class="ico-code sepH_b"><code>&lt;i class="icsw16-month-calendar icsw16-white"&gt;&lt;/i&gt;</code></div>
<ul class="ico-list the-icons clearfix">
<li><i class="icsw16-abacus"></i></li>
<li><i class="icsw16-acces-denied-sign"></i></li>
<li><i class="icsw16-address-book"></i></li>
<li><i class="icsw16-admin-user-2"></i></li>
<li><i class="icsw16-admin-user"></i></li>
<li><i class="icsw16-airplane"></i></li>
<li><i class="icsw16-alarm-clock"></i></li>
<li><i class="icsw16-alarm-bell-2"></i></li>
<li><i class="icsw16-alarm-bell"></i></li>
<li><i class="icsw16-alert-2"></i></li>
<li><i class="icsw16-alert"></i></li>
<li><i class="icsw16-apartment-building"></i></li>
<li><i class="icsw16-archive"></i></li>
<li><i class="icsw16-bag"></i></li>
<li><i class="icsw16-balloons"></i></li>
<li><i class="icsw16-bandaid"></i></li>
<li><i class="icsw16-battery-almost-empty"></i></li>
<li><i class="icsw16-battery-almost-full"></i></li>
<li><i class="icsw16-battery-empty"></i></li>
<li><i class="icsw16-battery-full"></i></li>
<li><i class="icsw16-battery"></i></li>
<li><i class="icsw16-bended-arrow-down"></i></li>
<li><i class="icsw16-bended-arrow-left"></i></li>
<li><i class="icsw16-bended-arrow-right"></i></li>
<li><i class="icsw16-bended-arrow-up"></i></li>
<li><i class="icsw16-big-brush"></i></li>
<li><i class="icsw16-blocks-images"></i></li>
<li><i class="icsw16-bluetooth-2"></i></li>
<li><i class="icsw16-bluetooth"></i></li>
<li><i class="icsw16-book-large"></i></li>
<li><i class="icsw16-book"></i></li>
<li><i class="icsw16-books"></i></li>
<li><i class="icsw16-box-incoming"></i></li>
<li><i class="icsw16-box-outgoing"></i></li>
<li><i class="icsw16-bulls-eye"></i></li>
<li><i class="icsw16-cd"></i></li>
<li><i class="icsw16-calculator"></i></li>
<li><i class="icsw16-camera-2"></i></li>
<li><i class="icsw16-camera"></i></li>
<li><i class="icsw16-car"></i></li>
<li><i class="icsw16-cash-register"></i></li>
<li><i class="icsw16-cassette"></i></li>
<li><i class="icsw16-cat"></i></li>
<li><i class="icsw16-chair"></i></li>
<li><i class="icsw16-chart-2"></i></li>
<li><i class="icsw16-chart-3"></i></li>
<li><i class="icsw16-chart-4"></i></li>
<li><i class="icsw16-chart-5"></i></li>
<li><i class="icsw16-chart-6"></i></li>
<li><i class="icsw16-chart-7"></i></li>
<li><i class="icsw16-chart-8"></i></li>
<li><i class="icsw16-chart"></i></li>
<li><i class="icsw16-chemical"></i></li>
<li><i class="icsw16-chrome"></i></li>
<li><i class="icsw16-clipboard"></i></li>
<li><i class="icsw16-clock"></i></li>
<li><i class="icsw16-cloud-download"></i></li>
<li><i class="icsw16-cloud-upload"></i></li>
<li><i class="icsw16-cloud"></i></li>
<li><i class="icsw16-cog-2"></i></li>
<li><i class="icsw16-cog-3"></i></li>
<li><i class="icsw16-cog-4"></i></li>
<li><i class="icsw16-cog"></i></li>
<li><i class="icsw16-companies"></i></li>
<li><i class="icsw16-computer_imac"></i></li>
<li><i class="icsw16-coverflow"></i></li>
<li><i class="icsw16-create-write"></i></li>
<li><i class="icsw16-cup"></i></li>
<li><i class="icsw16-cut-scissors"></i></li>
<li><i class="icsw16-dvd"></i></li>
<li><i class="icsw16-day-calendar"></i></li>
<li><i class="icsw16-document"></i></li>
<li><i class="icsw16-documents"></i></li>
<li><i class="icsw16-download-to-computer"></i></li>
<li><i class="icsw16-download"></i></li>
<li><i class="icsw16-dress"></i></li>
<li><i class="icsw16-electricity-input"></i></li>
<li><i class="icsw16-electricity-plug"></i></li>
<li><i class="icsw16-excel-document"></i></li>
<li><i class="icsw16-excel-documents"></i></li>
<li><i class="icsw16-exit"></i></li>
<li><i class="icsw16-expose"></i></li>
<li><i class="icsw16-eyedropper"></i></li>
<li><i class="icsw16-facebook-like-2"></i></li>
<li><i class="icsw16-facebook-like"></i></li>
<li><i class="icsw16-fax"></i></li>
<li><i class="icsw16-female-contour"></i></li>
<li><i class="icsw16-female-symbol"></i></li>
<li><i class="icsw16-file-cabinet"></i></li>
<li><i class="icsw16-film-camera"></i></li>
<li><i class="icsw16-film-strip-2"></i></li>
<li><i class="icsw16-film-strip"></i></li>
<li><i class="icsw16-finish-flag"></i></li>
<li><i class="icsw16-firefox"></i></li>
<li><i class="icsw16-flag-2"></i></li>
<li><i class="icsw16-flag"></i></li>
<li><i class="icsw16-folder"></i></li>
<li><i class="icsw16-footprints"></i></li>
<li><i class="icsw16-fountain-pen"></i></li>
<li><i class="icsw16-frames"></i></li>
<li><i class="icsw16-globe-2"></i></li>
<li><i class="icsw16-globe"></i></li>
<li><i class="icsw16-go-back-from-full-screen"></i></li>
<li><i class="icsw16-go-back-from-screen"></i></li>
<li><i class="icsw16-go-full-screen"></i></li>
<li><i class="icsw16-google-maps"></i></li>
<li><i class="icsw16-graph"></i></li>
<li><i class="icsw16-hd-2"></i></li>
<li><i class="icsw16-hd-3"></i></li>
<li><i class="icsw16-hd"></i></li>
<li><i class="icsw16-headphones"></i></li>
<li><i class="icsw16-help"></i></li>
<li><i class="icsw16-home-2"></i></li>
<li><i class="icsw16-home"></i></li>
<li><i class="icsw16-ice-cream-2"></i></li>
<li><i class="icsw16-ice-cream"></i></li>
<li><i class="icsw16-image-1"></i></li>
<li><i class="icsw16-image-2"></i></li>
<li><i class="icsw16-image"></i></li>
<li><i class="icsw16-image2-2"></i></li>
<li><i class="icsw16-inbox"></i></li>
<li><i class="icsw16-info-about"></i></li>
<li><i class="icsw16-key-2"></i></li>
<li><i class="icsw16-key"></i></li>
<li><i class="icsw16-ladys-purse"></i></li>
<li><i class="icsw16-lamp"></i></li>
<li><i class="icsw16-laptop"></i></li>
<li><i class="icsw16-lemonade-stand"></i></li>
<li><i class="icsw16-light-bulb"></i></li>
<li><i class="icsw16-link-2"></i></li>
<li><i class="icsw16-link"></i></li>
<li><i class="icsw16-list-w_-image"></i></li>
<li><i class="icsw16-list-w_-images"></i></li>
<li><i class="icsw16-list"></i></li>
<li><i class="icsw16-loading-bar"></i></li>
<li><i class="icsw16-locked-2"></i></li>
<li><i class="icsw16-locked"></i></li>
<li><i class="icsw16-magic-mouse"></i></li>
<li><i class="icsw16-magnifying-glass"></i></li>
<li><i class="icsw16-mail"></i></li>
<li><i class="icsw16-male-contour"></i></li>
<li><i class="icsw16-male-symbol"></i></li>
<li><i class="icsw16-map"></i></li>
<li><i class="icsw16-marker"></i></li>
<li><i class="icsw16-medical-case"></i></li>
<li><i class="icsw16-megaphone"></i></li>
<li><i class="icsw16-microphone"></i></li>
<li><i class="icsw16-mighty-mouse"></i></li>
<li><i class="icsw16-mobile-phone"></i></li>
<li><i class="icsw16-money-2"></i></li>
<li><i class="icsw16-money"></i></li>
<li><i class="icsw16-monitor"></i></li>
<li><i class="icsw16-month-calendar"></i></li>
<li><i class="icsw16-mouse-wires"></i></li>
<li><i class="icsw16-note-book"></i></li>
<li><i class="icsw16-pdf-document"></i></li>
<li><i class="icsw16-pdf-documents"></i></li>
<li><i class="icsw16-pacman-ghost"></i></li>
<li><i class="icsw16-pacman"></i></li>
<li><i class="icsw16-paint-brush"></i></li>
<li><i class="icsw16-pants"></i></li>
<li><i class="icsw16-paperclip"></i></li>
<li><i class="icsw16-pencil"></i></li>
<li><i class="icsw16-phone-3"></i></li>
<li><i class="icsw16-phone-hook"></i></li>
<li><i class="icsw16-phone"></i></li>
<li><i class="icsw16-piggy-bank"></i></li>
<li><i class="icsw16-plane-suitcase"></i></li>
<li><i class="icsw16-post-card"></i></li>
<li><i class="icsw16-power"></i></li>
<li><i class="icsw16-powerpoint-document"></i></li>
<li><i class="icsw16-powerpoint-documents"></i></li>
<li><i class="icsw16-presentation"></i></li>
<li><i class="icsw16-preview"></i></li>
<li><i class="icsw16-price-tag"></i></li>
<li><i class="icsw16-price-tags"></i></li>
<li><i class="icsw16-printer"></i></li>
<li><i class="icsw16-rss"></i></li>
<li><i class="icsw16-radio"></i></li>
<li><i class="icsw16-record"></i></li>
<li><i class="icsw16-recycle-symbol"></i></li>
<li><i class="icsw16-refresh-2"></i></li>
<li><i class="icsw16-refresh-3"></i></li>
<li><i class="icsw16-refresh-4"></i></li>
<li><i class="icsw16-refresh"></i></li>
<li><i class="icsw16-repeat"></i></li>
<li><i class="icsw16-robot"></i></li>
<li><i class="icsw16-ruler-2"></i></li>
<li><i class="icsw16-ruler"></i></li>
<li><i class="icsw16-running-man"></i></li>
<li><i class="icsw16-sd-2"></i></li>
<li><i class="icsw16-sd-3"></i></li>
<li><i class="icsw16-sd"></i></li>
<li><i class="icsw16-safari"></i></li>
<li><i class="icsw16-scan-label-2"></i></li>
<li><i class="icsw16-settings-2"></i></li>
<li><i class="icsw16-settings"></i></li>
<li><i class="icsw16-shopping-bag"></i></li>
<li><i class="icsw16-shopping-basket-21"></i></li>
<li><i class="icsw16-shopping-basket-2"></i></li>
<li><i class="icsw16-shopping-cart-2"></i></li>
<li><i class="icsw16-shopping-cart-3"></i></li>
<li><i class="icsw16-shopping-cart-4"></i></li>
<li><i class="icsw16-shopping-cart"></i></li>
<li><i class="icsw16-shuffle"></i></li>
<li><i class="icsw16-sign-post"></i></li>
<li><i class="icsw16-sleeveless-shirt"></i></li>
<li><i class="icsw16-small-brush"></i></li>
<li><i class="icsw16-socks"></i></li>
<li><i class="icsw16-sound"></i></li>
<li><i class="icsw16-speech-bubble-2"></i></li>
<li><i class="icsw16-speech-bubble"></i></li>
<li><i class="icsw16-speech-bubbles-2"></i></li>
<li><i class="icsw16-speech-bubbles"></i></li>
<li><i class="icsw16-sport-shirt"></i></li>
<li><i class="icsw16-stop-watch"></i></li>
<li><i class="icsw16-strategy-2"></i></li>
<li><i class="icsw16-strategy"></i></li>
<li><i class="icsw16-suitcase"></i></li>
<li><i class="icsw16-sweater"></i></li>
<li><i class="icsw16-t-shirt"></i></li>
<li><i class="icsw16-table"></i></li>
<li><i class="icsw16-tag"></i></li>
<li><i class="icsw16-tags-2"></i></li>
<li><i class="icsw16-television"></i></li>
<li><i class="icsw16-timer"></i></li>
<li><i class="icsw16-trashcan-2"></i></li>
<li><i class="icsw16-trashcan"></i></li>
<li><i class="icsw16-travel-suitcase"></i></li>
<li><i class="icsw16-tree"></i></li>
<li><i class="icsw16-trolly"></i></li>
<li><i class="icsw16-truck"></i></li>
<li><i class="icsw16-twitter-2"></i></li>
<li><i class="icsw16-twitter-3"></i></li>
<li><i class="icsw16-twitter"></i></li>
<li><i class="icsw16-umbrella"></i></li>
<li><i class="icsw16-under-construction"></i></li>
<li><i class="icsw16-unlocked"></i></li>
<li><i class="icsw16-upload"></i></li>
<li><i class="icsw16-user-2"></i></li>
<li><i class="icsw16-user-comment"></i></li>
<li><i class="icsw16-user"></i></li>
<li><i class="icsw16-users-2"></i></li>
<li><i class="icsw16-users"></i></li>
<li><i class="icsw16-v-card-2"></i></li>
<li><i class="icsw16-v-card"></i></li>
<li><i class="icsw16-vault"></i></li>
<li><i class="icsw16-vimeo-2"></i></li>
<li><i class="icsw16-vimeo"></i></li>
<li><i class="icsw16-walking-man"></i></li>
<li><i class="icsw16-wifi-signal-2"></i></li>
<li><i class="icsw16-wifi-signal"></i></li>
<li><i class="icsw16-winner-podium"></i></li>
<li><i class="icsw16-word-document"></i></li>
<li><i class="icsw16-word-documents"></i></li>
<li><i class="icsw16-youtube-2"></i></li>
<li><i class="icsw16-youtube"></i></li>
<li><i class="icsw16-zip-file"></i></li>
<li><i class="icsw16-zip-files"></i></li>
<li><i class="icsw16-ipad"></i></li>
<li><i class="icsw16-iphone-3g"></i></li>
<li><i class="icsw16-iphone-4"></i></li>
<li><i class="icsw16-ipod-classic"></i></li>
<li><i class="icsw16-ipod-nano"></i></li>
</ul>
<ul class="ico-list ico-list-dark">
<li><i class="icsw16-abacus icsw16-white"></i></li>
<li><i class="icsw16-acces-denied-sign icsw16-white"></i></li>
<li><i class="icsw16-address-book icsw16-white"></i></li>
<li><i class="icsw16-admin-user-2 icsw16-white"></i></li>
<li><i class="icsw16-admin-user icsw16-white"></i></li>
<li><i class="icsw16-airplane icsw16-white"></i></li>
<li><i class="icsw16-alarm-clock icsw16-white"></i></li>
<li><i class="icsw16-alarm-bell-2 icsw16-white"></i></li>
<li><i class="icsw16-alarm-bell icsw16-white"></i></li>
<li><i class="icsw16-alert-2 icsw16-white"></i></li>
<li><i class="icsw16-alert icsw16-white"></i></li>
<li><i class="icsw16-apartment-building icsw16-white"></i></li>
<li><i class="icsw16-archive icsw16-white"></i></li>
<li><i class="icsw16-bag icsw16-white"></i></li>
<li><i class="icsw16-balloons icsw16-white"></i></li>
<li><i class="icsw16-bandaid icsw16-white"></i></li>
<li><i class="icsw16-battery-almost-empty icsw16-white"></i></li>
<li><i class="icsw16-battery-almost-full icsw16-white"></i></li>
<li><i class="icsw16-battery-empty icsw16-white"></i></li>
<li><i class="icsw16-battery-full icsw16-white"></i></li>
<li><i class="icsw16-battery icsw16-white"></i></li>
<li><i class="icsw16-bended-arrow-down icsw16-white"></i></li>
<li><i class="icsw16-bended-arrow-left icsw16-white"></i></li>
<li><i class="icsw16-bended-arrow-right icsw16-white"></i></li>
<li><i class="icsw16-bended-arrow-up icsw16-white"></i></li>
<li><i class="icsw16-big-brush icsw16-white"></i></li>
<li><i class="icsw16-blocks-images icsw16-white"></i></li>
<li><i class="icsw16-bluetooth-2 icsw16-white"></i></li>
<li><i class="icsw16-bluetooth icsw16-white"></i></li>
<li><i class="icsw16-book-large icsw16-white"></i></li>
<li><i class="icsw16-book icsw16-white"></i></li>
<li><i class="icsw16-books icsw16-white"></i></li>
<li><i class="icsw16-box-incoming icsw16-white"></i></li>
<li><i class="icsw16-box-outgoing icsw16-white"></i></li>
<li><i class="icsw16-bulls-eye icsw16-white"></i></li>
<li><i class="icsw16-cd icsw16-white"></i></li>
<li><i class="icsw16-calculator icsw16-white"></i></li>
<li><i class="icsw16-camera-2 icsw16-white"></i></li>
<li><i class="icsw16-camera icsw16-white"></i></li>
<li><i class="icsw16-car icsw16-white"></i></li>
<li><i class="icsw16-cash-register icsw16-white"></i></li>
<li><i class="icsw16-cassette icsw16-white"></i></li>
<li><i class="icsw16-cat icsw16-white"></i></li>
<li><i class="icsw16-chair icsw16-white"></i></li>
<li><i class="icsw16-chart-2 icsw16-white"></i></li>
<li><i class="icsw16-chart-3 icsw16-white"></i></li>
<li><i class="icsw16-chart-4 icsw16-white"></i></li>
<li><i class="icsw16-chart-5 icsw16-white"></i></li>
<li><i class="icsw16-chart-6 icsw16-white"></i></li>
<li><i class="icsw16-chart-7 icsw16-white"></i></li>
<li><i class="icsw16-chart-8 icsw16-white"></i></li>
<li><i class="icsw16-chart icsw16-white"></i></li>
<li><i class="icsw16-chemical icsw16-white"></i></li>
<li><i class="icsw16-chrome icsw16-white"></i></li>
<li><i class="icsw16-clipboard icsw16-white"></i></li>
<li><i class="icsw16-clock icsw16-white"></i></li>
<li><i class="icsw16-cloud-download icsw16-white"></i></li>
<li><i class="icsw16-cloud-upload icsw16-white"></i></li>
<li><i class="icsw16-cloud icsw16-white"></i></li>
<li><i class="icsw16-cog-2 icsw16-white"></i></li>
<li><i class="icsw16-cog-3 icsw16-white"></i></li>
<li><i class="icsw16-cog-4 icsw16-white"></i></li>
<li><i class="icsw16-cog icsw16-white"></i></li>
<li><i class="icsw16-companies icsw16-white"></i></li>
<li><i class="icsw16-computer_imac icsw16-white"></i></li>
<li><i class="icsw16-coverflow icsw16-white"></i></li>
<li><i class="icsw16-create-write icsw16-white"></i></li>
<li><i class="icsw16-cup icsw16-white"></i></li>
<li><i class="icsw16-cut-scissors icsw16-white"></i></li>
<li><i class="icsw16-dvd icsw16-white"></i></li>
<li><i class="icsw16-day-calendar icsw16-white"></i></li>
<li><i class="icsw16-document icsw16-white"></i></li>
<li><i class="icsw16-documents icsw16-white"></i></li>
<li><i class="icsw16-download-to-computer icsw16-white"></i></li>
<li><i class="icsw16-download icsw16-white"></i></li>
<li><i class="icsw16-dress icsw16-white"></i></li>
<li><i class="icsw16-electricity-input icsw16-white"></i></li>
<li><i class="icsw16-electricity-plug icsw16-white"></i></li>
<li><i class="icsw16-excel-document icsw16-white"></i></li>
<li><i class="icsw16-excel-documents icsw16-white"></i></li>
<li><i class="icsw16-exit icsw16-white"></i></li>
<li><i class="icsw16-expose icsw16-white"></i></li>
<li><i class="icsw16-eyedropper icsw16-white"></i></li>
<li><i class="icsw16-facebook-like-2 icsw16-white"></i></li>
<li><i class="icsw16-facebook-like icsw16-white"></i></li>
<li><i class="icsw16-fax icsw16-white"></i></li>
<li><i class="icsw16-female-contour icsw16-white"></i></li>
<li><i class="icsw16-female-symbol icsw16-white"></i></li>
<li><i class="icsw16-file-cabinet icsw16-white"></i></li>
<li><i class="icsw16-film-camera icsw16-white"></i></li>
<li><i class="icsw16-film-strip-2 icsw16-white"></i></li>
<li><i class="icsw16-film-strip icsw16-white"></i></li>
<li><i class="icsw16-finish-flag icsw16-white"></i></li>
<li><i class="icsw16-firefox icsw16-white"></i></li>
<li><i class="icsw16-flag-2 icsw16-white"></i></li>
<li><i class="icsw16-flag icsw16-white"></i></li>
<li><i class="icsw16-folder icsw16-white"></i></li>
<li><i class="icsw16-footprints icsw16-white"></i></li>
<li><i class="icsw16-fountain-pen icsw16-white"></i></li>
<li><i class="icsw16-frames icsw16-white"></i></li>
<li><i class="icsw16-globe-2 icsw16-white"></i></li>
<li><i class="icsw16-globe icsw16-white"></i></li>
<li><i class="icsw16-go-back-from-full-screen icsw16-white"></i></li>
<li><i class="icsw16-go-back-from-screen icsw16-white"></i></li>
<li><i class="icsw16-go-full-screen icsw16-white"></i></li>
<li><i class="icsw16-google-maps icsw16-white"></i></li>
<li><i class="icsw16-graph icsw16-white"></i></li>
<li><i class="icsw16-hd-2 icsw16-white"></i></li>
<li><i class="icsw16-hd-3 icsw16-white"></i></li>
<li><i class="icsw16-hd icsw16-white"></i></li>
<li><i class="icsw16-headphones icsw16-white"></i></li>
<li><i class="icsw16-help icsw16-white"></i></li>
<li><i class="icsw16-home-2 icsw16-white"></i></li>
<li><i class="icsw16-home icsw16-white"></i></li>
<li><i class="icsw16-ice-cream-2 icsw16-white"></i></li>
<li><i class="icsw16-ice-cream icsw16-white"></i></li>
<li><i class="icsw16-image-1 icsw16-white"></i></li>
<li><i class="icsw16-image-2 icsw16-white"></i></li>
<li><i class="icsw16-image icsw16-white"></i></li>
<li><i class="icsw16-image2-2 icsw16-white"></i></li>
<li><i class="icsw16-inbox icsw16-white"></i></li>
<li><i class="icsw16-info-about icsw16-white"></i></li>
<li><i class="icsw16-key-2 icsw16-white"></i></li>
<li><i class="icsw16-key icsw16-white"></i></li>
<li><i class="icsw16-ladys-purse icsw16-white"></i></li>
<li><i class="icsw16-lamp icsw16-white"></i></li>
<li><i class="icsw16-laptop icsw16-white"></i></li>
<li><i class="icsw16-lemonade-stand icsw16-white"></i></li>
<li><i class="icsw16-light-bulb icsw16-white"></i></li>
<li><i class="icsw16-link-2 icsw16-white"></i></li>
<li><i class="icsw16-link icsw16-white"></i></li>
<li><i class="icsw16-list-w_-image icsw16-white"></i></li>
<li><i class="icsw16-list-w_-images icsw16-white"></i></li>
<li><i class="icsw16-list icsw16-white"></i></li>
<li><i class="icsw16-loading-bar icsw16-white"></i></li>
<li><i class="icsw16-locked-2 icsw16-white"></i></li>
<li><i class="icsw16-locked icsw16-white"></i></li>
<li><i class="icsw16-magic-mouse icsw16-white"></i></li>
<li><i class="icsw16-magnifying-glass icsw16-white"></i></li>
<li><i class="icsw16-mail icsw16-white"></i></li>
<li><i class="icsw16-male-contour icsw16-white"></i></li>
<li><i class="icsw16-male-symbol icsw16-white"></i></li>
<li><i class="icsw16-map icsw16-white"></i></li>
<li><i class="icsw16-marker icsw16-white"></i></li>
<li><i class="icsw16-medical-case icsw16-white"></i></li>
<li><i class="icsw16-megaphone icsw16-white"></i></li>
<li><i class="icsw16-microphone icsw16-white"></i></li>
<li><i class="icsw16-mighty-mouse icsw16-white"></i></li>
<li><i class="icsw16-mobile-phone icsw16-white"></i></li>
<li><i class="icsw16-money-2 icsw16-white"></i></li>
<li><i class="icsw16-money icsw16-white"></i></li>
<li><i class="icsw16-monitor icsw16-white"></i></li>
<li><i class="icsw16-month-calendar icsw16-white"></i></li>
<li><i class="icsw16-mouse-wires icsw16-white"></i></li>
<li><i class="icsw16-note-book icsw16-white"></i></li>
<li><i class="icsw16-pdf-document icsw16-white"></i></li>
<li><i class="icsw16-pdf-documents icsw16-white"></i></li>
<li><i class="icsw16-pacman-ghost icsw16-white"></i></li>
<li><i class="icsw16-pacman icsw16-white"></i></li>
<li><i class="icsw16-paint-brush icsw16-white"></i></li>
<li><i class="icsw16-pants icsw16-white"></i></li>
<li><i class="icsw16-paperclip icsw16-white"></i></li>
<li><i class="icsw16-pencil icsw16-white"></i></li>
<li><i class="icsw16-phone-3 icsw16-white"></i></li>
<li><i class="icsw16-phone-hook icsw16-white"></i></li>
<li><i class="icsw16-phone icsw16-white"></i></li>
<li><i class="icsw16-piggy-bank icsw16-white"></i></li>
<li><i class="icsw16-plane-suitcase icsw16-white"></i></li>
<li><i class="icsw16-post-card icsw16-white"></i></li>
<li><i class="icsw16-power icsw16-white"></i></li>
<li><i class="icsw16-powerpoint-document icsw16-white"></i></li>
<li><i class="icsw16-powerpoint-documents icsw16-white"></i></li>
<li><i class="icsw16-presentation icsw16-white"></i></li>
<li><i class="icsw16-preview icsw16-white"></i></li>
<li><i class="icsw16-price-tag icsw16-white"></i></li>
<li><i class="icsw16-price-tags icsw16-white"></i></li>
<li><i class="icsw16-printer icsw16-white"></i></li>
<li><i class="icsw16-rss icsw16-white"></i></li>
<li><i class="icsw16-radio icsw16-white"></i></li>
<li><i class="icsw16-record icsw16-white"></i></li>
<li><i class="icsw16-recycle-symbol icsw16-white"></i></li>
<li><i class="icsw16-refresh-2 icsw16-white"></i></li>
<li><i class="icsw16-refresh-3 icsw16-white"></i></li>
<li><i class="icsw16-refresh-4 icsw16-white"></i></li>
<li><i class="icsw16-refresh icsw16-white"></i></li>
<li><i class="icsw16-repeat icsw16-white"></i></li>
<li><i class="icsw16-robot icsw16-white"></i></li>
<li><i class="icsw16-ruler-2 icsw16-white"></i></li>
<li><i class="icsw16-ruler icsw16-white"></i></li>
<li><i class="icsw16-running-man icsw16-white"></i></li>
<li><i class="icsw16-sd-2 icsw16-white"></i></li>
<li><i class="icsw16-sd-3 icsw16-white"></i></li>
<li><i class="icsw16-sd icsw16-white"></i></li>
<li><i class="icsw16-safari icsw16-white"></i></li>
<li><i class="icsw16-scan-label-2 icsw16-white"></i></li>
<li><i class="icsw16-settings-2 icsw16-white"></i></li>
<li><i class="icsw16-settings icsw16-white"></i></li>
<li><i class="icsw16-shopping-bag icsw16-white"></i></li>
<li><i class="icsw16-shopping-basket-21 icsw16-white"></i></li>
<li><i class="icsw16-shopping-basket-2 icsw16-white"></i></li>
<li><i class="icsw16-shopping-cart-2 icsw16-white"></i></li>
<li><i class="icsw16-shopping-cart-3 icsw16-white"></i></li>
<li><i class="icsw16-shopping-cart-4 icsw16-white"></i></li>
<li><i class="icsw16-shopping-cart icsw16-white"></i></li>
<li><i class="icsw16-shuffle icsw16-white"></i></li>
<li><i class="icsw16-sign-post icsw16-white"></i></li>
<li><i class="icsw16-sleeveless-shirt icsw16-white"></i></li>
<li><i class="icsw16-small-brush icsw16-white"></i></li>
<li><i class="icsw16-socks icsw16-white"></i></li>
<li><i class="icsw16-sound icsw16-white"></i></li>
<li><i class="icsw16-speech-bubble-2 icsw16-white"></i></li>
<li><i class="icsw16-speech-bubble icsw16-white"></i></li>
<li><i class="icsw16-speech-bubbles-2 icsw16-white"></i></li>
<li><i class="icsw16-speech-bubbles icsw16-white"></i></li>
<li><i class="icsw16-sport-shirt icsw16-white"></i></li>
<li><i class="icsw16-stop-watch icsw16-white"></i></li>
<li><i class="icsw16-strategy-2 icsw16-white"></i></li>
<li><i class="icsw16-strategy icsw16-white"></i></li>
<li><i class="icsw16-suitcase icsw16-white"></i></li>
<li><i class="icsw16-sweater icsw16-white"></i></li>
<li><i class="icsw16-t-shirt icsw16-white"></i></li>
<li><i class="icsw16-table icsw16-white"></i></li>
<li><i class="icsw16-tag icsw16-white"></i></li>
<li><i class="icsw16-tags-2 icsw16-white"></i></li>
<li><i class="icsw16-television icsw16-white"></i></li>
<li><i class="icsw16-timer icsw16-white"></i></li>
<li><i class="icsw16-trashcan-2 icsw16-white"></i></li>
<li><i class="icsw16-trashcan icsw16-white"></i></li>
<li><i class="icsw16-travel-suitcase icsw16-white"></i></li>
<li><i class="icsw16-tree icsw16-white"></i></li>
<li><i class="icsw16-trolly icsw16-white"></i></li>
<li><i class="icsw16-truck icsw16-white"></i></li>
<li><i class="icsw16-twitter-2 icsw16-white"></i></li>
<li><i class="icsw16-twitter-3 icsw16-white"></i></li>
<li><i class="icsw16-twitter icsw16-white"></i></li>
<li><i class="icsw16-umbrella icsw16-white"></i></li>
<li><i class="icsw16-under-construction icsw16-white"></i></li>
<li><i class="icsw16-unlocked icsw16-white"></i></li>
<li><i class="icsw16-upload icsw16-white"></i></li>
<li><i class="icsw16-user-2 icsw16-white"></i></li>
<li><i class="icsw16-user-comment icsw16-white"></i></li>
<li><i class="icsw16-user icsw16-white"></i></li>
<li><i class="icsw16-users-2 icsw16-white"></i></li>
<li><i class="icsw16-users icsw16-white"></i></li>
<li><i class="icsw16-v-card-2 icsw16-white"></i></li>
<li><i class="icsw16-v-card icsw16-white"></i></li>
<li><i class="icsw16-vault icsw16-white"></i></li>
<li><i class="icsw16-vimeo-2 icsw16-white"></i></li>
<li><i class="icsw16-vimeo icsw16-white"></i></li>
<li><i class="icsw16-walking-man icsw16-white"></i></li>
<li><i class="icsw16-wifi-signal-2 icsw16-white"></i></li>
<li><i class="icsw16-wifi-signal icsw16-white"></i></li>
<li><i class="icsw16-winner-podium icsw16-white"></i></li>
<li><i class="icsw16-word-document icsw16-white"></i></li>
<li><i class="icsw16-word-documents icsw16-white"></i></li>
<li><i class="icsw16-youtube-2 icsw16-white"></i></li>
<li><i class="icsw16-youtube icsw16-white"></i></li>
<li><i class="icsw16-zip-file icsw16-white"></i></li>
<li><i class="icsw16-zip-files icsw16-white"></i></li>
<li><i class="icsw16-ipad icsw16-white"></i></li>
<li><i class="icsw16-iphone-3g icsw16-white"></i></li>
<li><i class="icsw16-iphone-4 icsw16-white"></i></li>
<li><i class="icsw16-ipod-classic icsw16-white"></i></li>
<li><i class="icsw16-ipod-nano icsw16-white"></i></li>
</ul>
</div>
</div>
<div class="w-box">
<div class="w-box-header">
    <h4>Splashy</h4>
</div>
<div class="w-box-content cnt_a">
<div class="ico-code sepH_b"><code>&lt;i class="splashy-arrow_state_grey_expanded"&gt;&lt;/i&gt;</code></div>
<ul class="ico-list">
<li><i class="splashy-add"></i></li>
<li><i class="splashy-add_outline"></i></li>
<li><i class="splashy-add_small"></i></li>
<li><i class="splashy-applications_windows"></i></li>
<li><i class="splashy-application_windows"></i></li>
<li><i class="splashy-application_windows_add"></i></li>
<li><i class="splashy-application_windows_down"></i></li>
<li><i class="splashy-application_windows_edit"></i></li>
<li><i class="splashy-application_windows_locked"></i></li>
<li><i class="splashy-application_windows_new"></i></li>
<li><i class="splashy-application_windows_okay"></i></li>
<li><i class="splashy-application_windows_remove"></i></li>
<li><i class="splashy-application_windows_share"></i></li>
<li><i class="splashy-application_windows_up"></i></li>
<li><i class="splashy-application_windows_warning"></i></li>
<li><i class="splashy-arrow_large_down"></i></li>
<li><i class="splashy-arrow_large_down_outline"></i></li>
<li><i class="splashy-arrow_large_left"></i></li>
<li><i class="splashy-arrow_large_left_outline"></i></li>
<li><i class="splashy-arrow_large_right"></i></li>
<li><i class="splashy-arrow_large_right_outline"></i></li>
<li><i class="splashy-arrow_large_up"></i></li>
<li><i class="splashy-arrow_large_up_outline"></i></li>
<li><i class="splashy-arrow_medium_down"></i></li>
<li><i class="splashy-arrow_medium_left"></i></li>
<li><i class="splashy-arrow_medium_lower_left"></i></li>
<li><i class="splashy-arrow_medium_lower_right"></i></li>
<li><i class="splashy-arrow_medium_right"></i></li>
<li><i class="splashy-arrow_medium_up"></i></li>
<li><i class="splashy-arrow_medium_upper_left"></i></li>
<li><i class="splashy-arrow_medium_upper_right"></i></li>
<li><i class="splashy-arrow_small_down"></i></li>
<li><i class="splashy-arrow_small_left"></i></li>
<li><i class="splashy-arrow_small_right"></i></li>
<li><i class="splashy-arrow_small_up"></i></li>
<li><i class="splashy-arrow_state_blue_collapsed"></i></li>
<li><i class="splashy-arrow_state_blue_expanded"></i></li>
<li><i class="splashy-arrow_state_blue_left"></i></li>
<li><i class="splashy-arrow_state_blue_right"></i></li>
<li><i class="splashy-arrow_state_grey_collapsed"></i></li>
<li><i class="splashy-arrow_state_grey_expanded"></i></li>
<li><i class="splashy-arrow_state_grey_left"></i></li>
<li><i class="splashy-arrow_state_grey_right"></i></li>
<li><i class="splashy-box"></i></li>
<li><i class="splashy-box_add"></i></li>
<li><i class="splashy-box_edit"></i></li>
<li><i class="splashy-box_locked"></i></li>
<li><i class="splashy-box_new"></i></li>
<li><i class="splashy-box_okay"></i></li>
<li><i class="splashy-box_remove"></i></li>
<li><i class="splashy-box_share"></i></li>
<li><i class="splashy-box_warning"></i></li>
<li><i class="splashy-breadcrumb_separator_arrow_1_dot"></i></li>
<li><i class="splashy-breadcrumb_separator_arrow_2_dots"></i></li>
<li><i class="splashy-breadcrumb_separator_arrow_full"></i></li>
<li><i class="splashy-breadcrumb_separator_dark"></i></li>
<li><i class="splashy-breadcrumb_separator_light"></i></li>
<li><i class="splashy-bullet_blue"></i></li>
<li><i class="splashy-bullet_blue_arrow"></i></li>
<li><i class="splashy-bullet_blue_collapse"></i></li>
<li><i class="splashy-bullet_blue_collapse_small"></i></li>
<li><i class="splashy-bullet_blue_expand"></i></li>
<li><i class="splashy-bullet_blue_expand_small"></i></li>
<li><i class="splashy-bullet_blue_small"></i></li>
<li><i class="splashy-calendar_day"></i></li>
<li><i class="splashy-calendar_day_add"></i></li>
<li><i class="splashy-calendar_day_down"></i></li>
<li><i class="splashy-calendar_day_edit"></i></li>
<li><i class="splashy-calendar_day_event"></i></li>
<li><i class="splashy-calendar_day_new"></i></li>
<li><i class="splashy-calendar_day_remove"></i></li>
<li><i class="splashy-calendar_day_up"></i></li>
<li><i class="splashy-calendar_month"></i></li>
<li><i class="splashy-calendar_month_add"></i></li>
<li><i class="splashy-calendar_month_down"></i></li>
<li><i class="splashy-calendar_month_edit"></i></li>
<li><i class="splashy-calendar_month_new"></i></li>
<li><i class="splashy-calendar_month_remove"></i></li>
<li><i class="splashy-calendar_month_up"></i></li>
<li><i class="splashy-calendar_week"></i></li>
<li><i class="splashy-calendar_week_add"></i></li>
<li><i class="splashy-calendar_week_edit"></i></li>
<li><i class="splashy-calendar_week_remove"></i></li>
<li><i class="splashy-cellphone"></i></li>
<li><i class="splashy-check"></i></li>
<li><i class="splashy-close"></i></li>
<li><i class="splashy-comment"></i></li>
<li><i class="splashy-comments"></i></li>
<li><i class="splashy-comments_reply"></i></li>
<li><i class="splashy-comments_small"></i></li>
<li><i class="splashy-comment_alert"></i></li>
<li><i class="splashy-comment_new_1"></i></li>
<li><i class="splashy-comment_new_2"></i></li>
<li><i class="splashy-comment_question"></i></li>
<li><i class="splashy-comment_reply"></i></li>
<li><i class="splashy-contact_blue"></i></li>
<li><i class="splashy-contact_blue_add"></i></li>
<li><i class="splashy-contact_blue_edit"></i></li>
<li><i class="splashy-contact_blue_new"></i></li>
<li><i class="splashy-contact_blue_remove"></i></li>
<li><i class="splashy-contact_grey"></i></li>
<li><i class="splashy-contact_grey_add"></i></li>
<li><i class="splashy-contact_grey_edit"></i></li>
<li><i class="splashy-contact_grey_new"></i></li>
<li><i class="splashy-contact_grey_remove"></i></li>
<li><i class="splashy-diamonds_1"></i></li>
<li><i class="splashy-diamonds_2"></i></li>
<li><i class="splashy-diamonds_3"></i></li>
<li><i class="splashy-diamonds_4"></i></li>
<li><i class="splashy-documents"></i></li>
<li><i class="splashy-documents_add"></i></li>
<li><i class="splashy-documents_edit"></i></li>
<li><i class="splashy-documents_locked"></i></li>
<li><i class="splashy-documents_new"></i></li>
<li><i class="splashy-documents_okay"></i></li>
<li><i class="splashy-documents_remove"></i></li>
<li><i class="splashy-documents_share"></i></li>
<li><i class="splashy-documents_warning"></i></li>
<li><i class="splashy-document_a4"></i></li>
<li><i class="splashy-document_a4_add"></i></li>
<li><i class="splashy-document_a4_blank"></i></li>
<li><i class="splashy-document_a4_download"></i></li>
<li><i class="splashy-document_a4_edit"></i></li>
<li><i class="splashy-document_a4_locked"></i></li>
<li><i class="splashy-document_a4_marked"></i></li>
<li><i class="splashy-document_a4_new"></i></li>
<li><i class="splashy-document_a4_okay"></i></li>
<li><i class="splashy-document_a4_remove"></i></li>
<li><i class="splashy-document_a4_share"></i></li>
<li><i class="splashy-document_a4_upload"></i></li>
<li><i class="splashy-document_a4_warning"></i></li>
<li><i class="splashy-document_copy"></i></li>
<li><i class="splashy-document_letter"></i></li>
<li><i class="splashy-document_letter_add"></i></li>
<li><i class="splashy-document_letter_blank"></i></li>
<li><i class="splashy-document_letter_download"></i></li>
<li><i class="splashy-document_letter_edit"></i></li>
<li><i class="splashy-document_letter_locked"></i></li>
<li><i class="splashy-document_letter_marked"></i></li>
<li><i class="splashy-document_letter_new"></i></li>
<li><i class="splashy-document_letter_okay"></i></li>
<li><i class="splashy-document_letter_remove"></i></li>
<li><i class="splashy-document_letter_share"></i></li>
<li><i class="splashy-document_letter_upload"></i></li>
<li><i class="splashy-document_letter_warning"></i></li>
<li><i class="splashy-document_small"></i></li>
<li><i class="splashy-document_small_download"></i></li>
<li><i class="splashy-document_small_upload"></i></li>
<li><i class="splashy-download"></i></li>
<li><i class="splashy-error"></i></li>
<li><i class="splashy-error_do_not"></i></li>
<li><i class="splashy-error_do_not_small"></i></li>
<li><i class="splashy-error_small"></i></li>
<li><i class="splashy-error_x"></i></li>
<li><i class="splashy-fish"></i></li>
<li><i class="splashy-folder_classic"></i></li>
<li><i class="splashy-folder_classic_add"></i></li>
<li><i class="splashy-folder_classic_add_simple"></i></li>
<li><i class="splashy-folder_classic_down"></i></li>
<li><i class="splashy-folder_classic_edit"></i></li>
<li><i class="splashy-folder_classic_locked"></i></li>
<li><i class="splashy-folder_classic_opened"></i></li>
<li><i class="splashy-folder_classic_opened_stuffed"></i></li>
<li><i class="splashy-folder_classic_remove"></i></li>
<li><i class="splashy-folder_classic_remove_simple"></i></li>
<li><i class="splashy-folder_classic_stuffed"></i></li>
<li><i class="splashy-folder_classic_stuffed_add"></i></li>
<li><i class="splashy-folder_classic_stuffed_add_simple"></i></li>
<li><i class="splashy-folder_classic_stuffed_edit"></i></li>
<li><i class="splashy-folder_classic_stuffed_locked"></i></li>
<li><i class="splashy-folder_classic_stuffed_remove"></i></li>
<li><i class="splashy-folder_classic_stuffed_remove_simple"></i></li>
<li><i class="splashy-folder_classic_type_document"></i></li>
<li><i class="splashy-folder_classic_type_image"></i></li>
<li><i class="splashy-folder_classic_type_music"></i></li>
<li><i class="splashy-folder_classic_up"></i></li>
<li><i class="splashy-folder_locked"></i></li>
<li><i class="splashy-folder_modernist"></i></li>
<li><i class="splashy-folder_modernist_add"></i></li>
<li><i class="splashy-folder_modernist_add_simple"></i></li>
<li><i class="splashy-folder_modernist_down"></i></li>
<li><i class="splashy-folder_modernist_edit"></i></li>
<li><i class="splashy-folder_modernist_locked"></i></li>
<li><i class="splashy-folder_modernist_opened"></i></li>
<li><i class="splashy-folder_modernist_opened_stuffed"></i></li>
<li><i class="splashy-folder_modernist_remove"></i></li>
<li><i class="splashy-folder_modernist_remove_simple"></i></li>
<li><i class="splashy-folder_modernist_stuffed"></i></li>
<li><i class="splashy-folder_modernist_stuffed_add"></i></li>
<li><i class="splashy-folder_modernist_stuffed_add_simple"></i></li>
<li><i class="splashy-folder_modernist_stuffed_edit"></i></li>
<li><i class="splashy-folder_modernist_stuffed_locked"></i></li>
<li><i class="splashy-folder_modernist_stuffed_remove"></i></li>
<li><i class="splashy-folder_modernist_stuffed_remove_simple"></i></li>
<li><i class="splashy-folder_modernist_type_document"></i></li>
<li><i class="splashy-folder_modernist_type_image"></i></li>
<li><i class="splashy-folder_modernist_type_movie"></i></li>
<li><i class="splashy-folder_modernist_type_music"></i></li>
<li><i class="splashy-folder_modernist_up"></i></li>
<li><i class="splashy-folder_remove"></i></li>
<li><i class="splashy-folder_stuffed"></i></li>
<li><i class="splashy-folder_stuffed_add"></i></li>
<li><i class="splashy-folder_stuffed_locked"></i></li>
<li><i class="splashy-folder_stuffed_remove"></i></li>
<li><i class="splashy-gem_cancel_1"></i></li>
<li><i class="splashy-gem_cancel_2"></i></li>
<li><i class="splashy-gem_okay"></i></li>
<li><i class="splashy-gem_options"></i></li>
<li><i class="splashy-gem_remove"></i></li>
<li><i class="splashy-group_blue"></i></li>
<li><i class="splashy-group_blue_add"></i></li>
<li><i class="splashy-group_blue_edit"></i></li>
<li><i class="splashy-group_blue_new"></i></li>
<li><i class="splashy-group_blue_remove"></i></li>
<li><i class="splashy-group_green"></i></li>
<li><i class="splashy-group_green_add"></i></li>
<li><i class="splashy-group_green_edit"></i></li>
<li><i class="splashy-group_green_new"></i></li>
<li><i class="splashy-group_green_remove"></i></li>
<li><i class="splashy-group_grey"></i></li>
<li><i class="splashy-group_grey_add"></i></li>
<li><i class="splashy-group_grey_edit"></i></li>
<li><i class="splashy-group_grey_new"></i></li>
<li><i class="splashy-group_grey_remove"></i></li>
<li><i class="splashy-hcard"></i></li>
<li><i class="splashy-hcards"></i></li>
<li><i class="splashy-hcards_add"></i></li>
<li><i class="splashy-hcards_down"></i></li>
<li><i class="splashy-hcards_edit"></i></li>
<li><i class="splashy-hcards_remove"></i></li>
<li><i class="splashy-hcards_up"></i></li>
<li><i class="splashy-hcard_add"></i></li>
<li><i class="splashy-hcard_download"></i></li>
<li><i class="splashy-hcard_edit"></i></li>
<li><i class="splashy-hcard_new"></i></li>
<li><i class="splashy-hcard_remove"></i></li>
<li><i class="splashy-hcard_up"></i></li>
<li><i class="splashy-heart"></i></li>
<li><i class="splashy-heart_add"></i></li>
<li><i class="splashy-heart_edit"></i></li>
<li><i class="splashy-heart_outline"></i></li>
<li><i class="splashy-heart_remove"></i></li>
<li><i class="splashy-heart_up"></i></li>
<li><i class="splashy-help"></i></li>
<li><i class="splashy-home_green"></i></li>
<li><i class="splashy-home_grey"></i></li>
<li><i class="splashy-image_cultured"></i></li>
<li><i class="splashy-image_modernist"></i></li>
<li><i class="splashy-information"></i></li>
<li><i class="splashy-lock_large_locked"></i></li>
<li><i class="splashy-lock_large_unlocked"></i></li>
<li><i class="splashy-lock_small_locked"></i></li>
<li><i class="splashy-lock_small_unlocked"></i></li>
<li><i class="splashy-mail_light"></i></li>
<li><i class="splashy-mail_light_down"></i></li>
<li><i class="splashy-mail_light_left"></i></li>
<li><i class="splashy-mail_light_new_1"></i></li>
<li><i class="splashy-mail_light_new_2"></i></li>
<li><i class="splashy-mail_light_right"></i></li>
<li><i class="splashy-mail_light_stuffed"></i></li>
<li><i class="splashy-mail_light_up"></i></li>
<li><i class="splashy-map"></i></li>
<li><i class="splashy-marker_rounded_add"></i></li>
<li><i class="splashy-marker_rounded_blue"></i></li>
<li><i class="splashy-marker_rounded_edit"></i></li>
<li><i class="splashy-marker_rounded_green"></i></li>
<li><i class="splashy-marker_rounded_grey_1"></i></li>
<li><i class="splashy-marker_rounded_grey_2"></i></li>
<li><i class="splashy-marker_rounded_grey_3"></i></li>
<li><i class="splashy-marker_rounded_grey_4"></i></li>
<li><i class="splashy-marker_rounded_grey_5"></i></li>
<li><i class="splashy-marker_rounded_light_blue"></i></li>
<li><i class="splashy-marker_rounded_new"></i></li>
<li><i class="splashy-marker_rounded_red"></i></li>
<li><i class="splashy-marker_rounded_remove"></i></li>
<li><i class="splashy-marker_rounded_violet"></i></li>
<li><i class="splashy-marker_rounded_yellow"></i></li>
<li><i class="splashy-marker_rounded_yellow_green"></i></li>
<li><i class="splashy-marker_rounded_yellow_orange"></i></li>
<li><i class="splashy-media_controls_dark_first"></i></li>
<li><i class="splashy-media_controls_dark_forward"></i></li>
<li><i class="splashy-media_controls_dark_last"></i></li>
<li><i class="splashy-media_controls_dark_pause"></i></li>
<li><i class="splashy-media_controls_dark_play"></i></li>
<li><i class="splashy-media_controls_dark_rewind"></i></li>
<li><i class="splashy-media_controls_dark_stop"></i></li>
<li><i class="splashy-media_controls_first_small"></i></li>
<li><i class="splashy-media_controls_forward_small"></i></li>
<li><i class="splashy-media_controls_last_small"></i></li>
<li><i class="splashy-media_controls_pause_small"></i></li>
<li><i class="splashy-media_controls_play_small"></i></li>
<li><i class="splashy-media_controls_rewind_small"></i></li>
<li><i class="splashy-media_controls_stop_small"></i></li>
<li><i class="splashy-menu"></i></li>
<li><i class="splashy-menu_dropdown"></i></li>
<li><i class="splashy-movie_play"></i></li>
<li><i class="splashy-music_cd_blue_note"></i></li>
<li><i class="splashy-music_green"></i></li>
<li><i class="splashy-music_grey"></i></li>
<li><i class="splashy-new_small"></i></li>
<li><i class="splashy-okay"></i></li>
<li><i class="splashy-okay_small"></i></li>
<li><i class="splashy-pagination_1_first"></i></li>
<li><i class="splashy-pagination_1_last"></i></li>
<li><i class="splashy-pagination_1_next"></i></li>
<li><i class="splashy-pagination_1_previous"></i></li>
<li><i class="splashy-pencil"></i></li>
<li><i class="splashy-pencil_small"></i></li>
<li><i class="splashy-printer"></i></li>
<li><i class="splashy-quanitity_capsule_1"></i></li>
<li><i class="splashy-quantity_capsule_2"></i></li>
<li><i class="splashy-quantity_capsule_3"></i></li>
<li><i class="splashy-quantity_capsule_4"></i></li>
<li><i class="splashy-quantity_capsule_5"></i></li>
<li><i class="splashy-refresh"></i></li>
<li><i class="splashy-refresh_backwards"></i></li>
<li><i class="splashy-refresh_forward"></i></li>
<li><i class="splashy-remove"></i></li>
<li><i class="splashy-remove_minus_sign"></i></li>
<li><i class="splashy-remove_minus_sign_outline"></i></li>
<li><i class="splashy-remove_minus_sign_small"></i></li>
<li><i class="splashy-remove_outline"></i></li>
<li><i class="splashy-shield"></i></li>
<li><i class="splashy-shield_chevrons"></i></li>
<li><i class="splashy-shield_star"></i></li>
<li><i class="splashy-slider_no_pointy_thing"></i></li>
<li><i class="splashy-smiley_amused"></i></li>
<li><i class="splashy-smiley_happy"></i></li>
<li><i class="splashy-smiley_surprised"></i></li>
<li><i class="splashy-sprocket_dark"></i></li>
<li><i class="splashy-sprocket_light"></i></li>
<li><i class="splashy-star_boxed_empty"></i></li>
<li><i class="splashy-star_boxed_full"></i></li>
<li><i class="splashy-star_boxed_half"></i></li>
<li><i class="splashy-star_empty"></i></li>
<li><i class="splashy-star_full"></i></li>
<li><i class="splashy-star_half"></i></li>
<li><i class="splashy-tag"></i></li>
<li><i class="splashy-tag_add"></i></li>
<li><i class="splashy-tag_edit"></i></li>
<li><i class="splashy-tag_remove"></i></li>
<li><i class="splashy-thumb_down"></i></li>
<li><i class="splashy-thumb_up"></i></li>
<li><i class="splashy-ticket"></i></li>
<li><i class="splashy-ticket_add"></i></li>
<li><i class="splashy-ticket_remove"></i></li>
<li><i class="splashy-upload"></i></li>
<li><i class="splashy-view_list"></i></li>
<li><i class="splashy-view_list_with_thumbnail"></i></li>
<li><i class="splashy-view_outline"></i></li>
<li><i class="splashy-view_outline_detail"></i></li>
<li><i class="splashy-view_table"></i></li>
<li><i class="splashy-view_thumbnail"></i></li>
<li><i class="splashy-volume"></i></li>
<li><i class="splashy-volume_loud"></i></li>
<li><i class="splashy-volume_off"></i></li>
<li><i class="splashy-volume_quiet"></i></li>
<li><i class="splashy-warning"></i></li>
<li><i class="splashy-warning_triangle"></i></li>
<li><i class="splashy-warning_triangle_small"></i></li>
<li><i class="splashy-zoom"></i></li>
<li><i class="splashy-zoom_in"></i></li>
<li><i class="splashy-zoom_out"></i></li>
</ul>
</div>
</div>

</body>
</html>